### ISSUE TITLE
ff doesn't work as published

### ISSUE THREAD

**Issue by Shakedp** [yarox/pddl-examples#1]
~/workspace/Metric-FF-v2.0/ff -o domain.pddl -f problem.pddl

ff: parsing domain file
domain 'ROVER-DOMAIN' defined
 ... done.
ff: parsing problem file
problem 'ROVER-SINGLE' defined
 ... done.

warning: change on metric in wrong direction. no optimization done.
warning: numeric precondition. turning cost-minimizing relaxed plans OFF.

ff: search configuration is Enforced Hill-Climbing, then A*epsilon with weight 5.
Error! Optimization criterion not established.
A*epsilon not defined.

**Comment by ConnorSClair** [comment]
Same. The problems / domains don't work for me either...

**Comment by tomitrescak** [comment]
Does it work ? I'm getting the same error

**Comment by yarox** [comment]
Sorry, guys! This is really old code and I no longer remember what I did back then.

**Comment by LonyuNaz** [comment]
What helped was setting the flag at line 303 to TRUE:

Bool goptimization_established = TRUE;
